Lang:
  Prefix: "&f[&3ItemEffect&f] "
  NoPerm: 
  ReceiveItemEffect:



ItemEffect:
  "strenghtcookie":
    Material: COOKIE
    Data: 0
    Name: "&6&lSUPER COOKIE &f(Strength 01:20)"
    Lore: 
    - "&r"
    - "&f-> right clock this cookie to get strength effect !"
    - "&r"
    Effect:
      Type: STRENGTH
      Power: 1
      #You can change on EAT, RIGHT_CLICK, LEFT_CLICK   
      EffectOn: RIGHT_CLICK
      Duration: 120
  "speedapple":
    Material: GOLDEN_APPLE
    Data: 0
    Name: "&b&lSPEED APPLE &f(Speed 01:20)"
    Lore: 
    - "&r"
    - "&f-> eat this apple to get speed effect !"
    - "&r"
    Effect:
      Type: SPEED
      #You can change on EAT, RIGHT_CLICK, LEFT_CLICK   
      EffectOn: EAT
      Duration: 120
